love.load = ->
love.update = (dt) ->
love.draw = ->
love.mousepressed = (x, y, button) ->
love.mousereleased = (x, y, button) ->
love.keypressed = (key, unicode) ->
love.keyreleased = (key, unicode) ->
love.focus = (focus) ->
love.quit = ->
